---
title: "NEON download"
author: "Kari Norman"
date: "10/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(neonUtilities)
library(piggyback)
library(lubridate)
```

Download data
```{r}
beetle_dir <- here::here("data", "beetles_raw.rda")
if (file.exists(beetle_dir)){
  load(beetle_dir)
} else{
  beetles_raw <- loadByProduct("DP1.10022.001", check.size = FALSE)
  usethis::use_data(beetles_raw)
}
```

#### Clean and format raw data (following Tidy Neon code)
Clean up Data
```{r}
#function for finding the statistical mode
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

data <- beetles_raw$bet_fielddata %>%
  select(sampleID, domainID, siteID, plotID, trapID, setDate, collectDate, eventID, trappingDays) %>%
  #eventID's are inconsistently separated by periods, so remove
  mutate(eventID = str_remove_all(eventID, "[.]")) %>%
  # calculate a new trapdays column
  mutate(trappingDays = interval(ymd(setDate), ymd(collectDate)) %/% days(1))

#Find the traps that have multiple collectDates/bouts for the same setDate
#need to calculate their trap days from the previous collectDate, not the setDate
adjTrappingDays <- data %>%
  select(plotID, trapID, setDate, collectDate, trappingDays, eventID) %>%
  group_by_at(vars(-collectDate, -trappingDays, -eventID)) %>%
  filter(n_distinct(collectDate) > 1) %>%
  group_by(plotID, trapID, setDate) %>%
  mutate(diffTrappingDays = trappingDays - min(trappingDays)) %>%
  mutate(adjTrappingDays = case_when(
    diffTrappingDays == 0 ~ trappingDays,
    TRUE ~ diffTrappingDays
  )) %>%
  select(-c(trappingDays, diffTrappingDays))

data <- data %>%
  #update with adjusted trapping days where needed
  left_join(adjTrappingDays) %>%
  mutate(trappingDays = case_when(
    !is.na(adjTrappingDays) ~ adjTrappingDays,
    TRUE ~ trappingDays
  )) %>%
  select(-adjTrappingDays, -setDate) %>%
  #for some eventID's (bouts) collection happened over two days,
  #change collectDate to the date that majority of traps were collected on
  group_by(eventID) %>%
  mutate(collectDate = Mode(collectDate)) %>%
  ungroup() %>%
  #there are also some sites for which all traps were set and collect on the same date, but have multiple eventID's
  #we want to consider that as all one bout so we'll just create a new ID based on the site and collectDate
  unite(boutID, siteID, collectDate, remove = FALSE) %>%
  select(-eventID) %>%
  #and join to sample data
  left_join(beetles_raw$bet_sorting %>%
              filter(sampleType %in% c("carabid", "other carabid")) %>% #only want carabid samples, not bycatch
              select(sampleID, subsampleID, sampleType, taxonID, scientificName, taxonRank, individualCount),
            by = "sampleID") #%>%
  #filter(!is.na(subsampleID)) #even though they were marked a sampled, some collection times don't actually have any samples
 
```

Clean up taxonomic data
- prioritize expert first, the pinning, then sorting
```{r}
# Replace sorting taxon info with pinning taxon info (people that pin specimens are more experienced with taxonomy), where available
data_pin <- data %>%
  left_join(beetles_raw$bet_parataxonomistID %>% select(subsampleID, individualID, taxonID, scientificName, taxonRank), by = "subsampleID") %>%
  mutate_if(is.factor, as.character) %>%
  mutate(taxonID = ifelse(is.na(taxonID.y), taxonID.x, taxonID.y)) %>%
  mutate(taxonRank = ifelse(is.na(taxonRank.y), taxonRank.x, taxonRank.y)) %>%
  mutate(scientificName = ifelse(is.na(scientificName.y), scientificName.x, scientificName.y)) %>%
  mutate(identificationSource = ifelse(is.na(scientificName.y), "sort", "pin")) %>%
  select(-ends_with(".x"), -ends_with(".y"))

#some subsamples weren't fully ID'd by the pinners, so we have to recover the unpinned-individuals
lost_indv <- data_pin %>% 
  filter(!is.na(individualID)) %>%
  group_by(subsampleID, individualCount) %>%
  summarise(n_ided = n_distinct(individualID)) %>% 
  filter(n_ided < individualCount) %>%
  mutate(unidentifiedCount = individualCount - n_ided) %>%
  select(subsampleID, individualCount = unidentifiedCount) %>%
  left_join(data %>% select(-individualCount), by = "subsampleID") %>%
  mutate(identificationSource = "sort")

#add unpinned-individuals back to the pinned id's, adjust the individual counts so pinned individuals have a count of 1
data_pin <- data_pin %>%
  mutate(individualCount = ifelse(identificationSource == "sort", individualCount, 1)) %>%
  bind_rows(lost_indv)
```

Join expert data to existing pinning and sorting data
```{r}
#There are some individualID's for which experts ID'd more than one species we exclude them
ex_expert_id <- beetles_raw$bet_expertTaxonomistIDProcessed %>% 
  group_by(individualID) %>% 
  filter(n_distinct(taxonID) > 1) %>% 
  pull(individualID)

# Add expert taxonomy info, where available
data_expert <- left_join(data_pin, 
                      select(beetles_raw$bet_expertTaxonomistIDProcessed,
                             individualID,taxonID,scientificName,taxonRank) %>%
                        filter(!individualID %in% ex_expert_id), #exclude ID's that have unresolved expert taxonomy
                      by = 'individualID', na_matches = "never") %>% distinct()

# Replacement old taxon info with expert info, where available
data_expert <- data_expert %>%
  mutate_if(is.factor, as.character) %>%
  mutate(taxonID = ifelse(is.na(taxonID.y), taxonID.x, taxonID.y)) %>%
  mutate(taxonRank = ifelse(is.na(taxonRank.y), taxonRank.x, taxonRank.y)) %>%
  mutate(scientificName = ifelse(is.na(scientificName.y), scientificName.x, scientificName.y)) %>%
  mutate(identificationSource = ifelse(is.na(scientificName.y), identificationSource, "expert")) %>%
  select(-ends_with(".x"), -ends_with(".y"))

beetles_data <- data_expert
usethis::use_data(beetles_data)
```

Get raw counts table
```{r}
beetles_counts <- beetles_data %>%
  select(-c(subsampleID, sampleType, individualID, identificationSource)) %>%
  group_by_at(vars(-individualCount)) %>%
  summarise(count = sum(individualCount)) %>%
  ungroup()

usethis::use_data(beetles_counts)
```

# Formatting for analysis packages

Codyn Package formatting
```{r}
beetles <- beetles_counts %>%
  mutate(year = lubridate::year(collectDate)) %>%
  #remove traps with no samples, remove 2020
  filter(!is.na(taxonID), year != 2020) %>%
  select(-year)

# Calculate the total trapping days for a bout
bout_trap_days <- beetles %>%
  select(siteID, plotID, trapID, boutID, trappingDays) %>%
  distinct() %>%
  group_by(siteID, boutID) %>%
  mutate(totalTrapDays = sum(trappingDays)) %>%
  select(-c(trapID, plotID, trappingDays)) %>%
  distinct()

#Intra annual variability
beetles_site_bout <- beetles_counts %>% 
  filter(!is.na(count)) %>%
  select(siteID, boutID, collectDate, scientificName, count) %>%
  group_by(siteID, collectDate, boutID, scientificName) %>%
  mutate(abundance = sum(count)) %>%
  select(-count) %>%
  distinct() %>%
  ungroup() %>%
  left_join(bout_trap_days, by = c("siteID", "boutID"))

#Inter annual variability

#calculate trap days in a year 
yearly_trap_days <- bout_trap_days %>%
  mutate(year = substr(boutID, 6,9)) %>%
  group_by(siteID, year) %>%
  mutate(totalTrapDays = sum(totalTrapDays)) %>%
  select(-boutID) %>%
  distinct()

codyn_beetles_inter <- beetles_site_bout %>%
  mutate(year = substr(boutID, 6,9)) %>%
  select(-c(totalTrapDays, boutID, collectDate)) %>%
  group_by(siteID, year, scientificName) %>%
  mutate(abundance = sum(abundance)) %>%
  distinct() %>%
  left_join(yearly_trap_days, by = c("siteID", "year")) %>%
  mutate(cpue = abundance/totalTrapDays) %>%
  select(-c(abundance, totalTrapDays)) %>%
  ungroup()

codyn_beetles_intra <- beetles_site_bout %>%
  mutate(cpue = abundance/totalTrapDays) %>%
  select(-c(abundance, totalTrapDays))

#Only include data from sites that fit our sampling criteria of being sampled 
#for at least 4 years with 3 replicates
included_sites <- codyn_beetles_intra %>% 
  mutate(year = year(collectDate)) %>% 
  select(siteID, boutID, year) %>% 
  distinct() %>% count(siteID, year) %>% 
  filter(n > 2) %>% 
  group_by(siteID) %>% 
  filter(n_distinct(year) > 3) %>% 
  pull(siteID) %>% unique()

codyn_beetles_inter <- codyn_beetles_inter %>%
  filter(siteID %in% included_sites)

codyn_beetles_intra <- codyn_beetles_intra %>%
  filter(siteID %in% included_sites)

usethis::use_data(codyn_beetles_inter, codyn_beetles_intra)
```

BAT data
```{r}
BAT_beetles_intra <- codyn_beetles_intra %>%
  mutate(year = lubridate::year(collectDate),
         month = lubridate::month(collectDate),
         day = lubridate::day(collectDate)) %>%
  select(-collectDate) %>%
  spread(scientificName, cpue)

BAT_beetles_inter <- codyn_beetles_inter %>%
  spread(scientificName, cpue) 

usethis::use_data(BAT_beetles_intra, BAT_beetles_inter)
```
